version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG_NAME=mytag
    command: >
      sh -c "python3.8 manage.py runserver 0.0.0.0:8000"
    env_file: 
      - .env
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/src/jamiya

    depends_on:
      - redis
  redis:
    image: "redis:alpine"
