version: "3"

services:
  web:
    build: .
    command: >
      sh -c "python3.8 manage.py runserver 0.0.0.0:8000"
    env_file: 
      - .env
    ports: 
      - "8000:8000"
    volumes: 
      - .:/usr/src/jamiya
    # environment:
    #   - POSTGRES_HOST=${DB_HOST}
    #   - POSTGRES_DB=${DB_NAME}
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      # - db
      - redis
      # - elasticsearch
  redis:
    image: "redis:alpine"
  # db:
  #   image: postgres
  #   env_file: 
  #     - .env
  #   environment:
  #     - POSTGRES_HOST=${DB_HOST}
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
