from tkinter import SINGLE


INTERN = "INTERN"
FRONTDESK = "FRONTDESK"
BANK = "BANK"
DRIVER = "DRIVER"
ONLINE = "ONLINE"
HEAD_OF_MARKETING = "HEADOFMARKETING"
HEAD_OF_OPERATIONS = "HEADOFOPERATIONS"

ACTIVE = "ACTIVE"
RELEASED = "RELEASED"
SUSPENDED = "SUSPENDED"
LEAVE = "LEAVE"

DOLLAR = "DOLLAR"
NAIRA = "NAIRA"
POUND = "POUND"
EURO = "EURO"

CASH = "CASH"
TRANSFER = "TRANSFER"
DEPOSIT = "DEPOSIT"

SENT = "SENT"
INITIATED = "INITIATED"
DONE = "DONE"
FAILED = "FAILED"

SALES = "SALES"
PURCHASE = "PURCHASE"


SINGLE_PAYMENT = "SINGLE_PAYMENT"
DOUBLE_PAYMENT = "DOUBLE_PAYMENT"

RECIEVABLE = "RECIEVABLE"
PAYABLE = "PAYABLE"

ZENITH_BANK = "ZENITH BANK"
PROVIDUS_BANK = "PROVIDUS BANK"

EMPLOYEE_STATIONS = (
    (INTERN, "INTERN"),
    (FRONTDESK, "FRONT DESK"),
    (BANK, "BANK"),
    (DRIVER, "DRIVER"),
    (ONLINE, "ONLINE"),
    (HEAD_OF_MARKETING, "HEAD OF MARKETING"),
    (HEAD_OF_OPERATIONS, "HEAD OF OPERATIONS"),
)
EMPLOYEE_STATUS = (
    (ACTIVE, "ACTIVE"),
    (RELEASED, "RELEASED"),
    (SUSPENDED, "SUSPENSION"),
    (LEAVE, "LEAVE"),
)

CURRENCIES = (
    (NAIRA, "NAIRA"),
    (DOLLAR, "DOLLAR"),
    (POUND, "POUND"),
    (EURO, "EURO"),
)

MODE = (
    (CASH, "CASH"),
    (TRANSFER, "TRANSFER"),
    (DEPOSIT, "DEPOSIT"),
)

TRANSACTION_STATUS = (
    (SENT, "SENT"),
    (INITIATED, "INITIATED"),
    (DONE, "APPROVED"),
    (FAILED, "FAILED"),
)

CATEGORIES = (
    (SALES, "SALES"),
    (PURCHASE, "PURCHASE"),
)


PAYMENT = (
    (SINGLE_PAYMENT, "SINGLE PAYMENT"),
    (DOUBLE_PAYMENT, "DOUBLE PAYMENT"),
)

DEBTORS = (
    (RECIEVABLE, "RECIEVABLE"),
    (PAYABLE, "PAYABLE"),
)
BANKS = ((ZENITH_BANK, "ZENITH BANK"), (PROVIDUS_BANK, "PROVIDUS BANK"))
