from tkinter import SINGLE


INTERN = "INTERN"
FRONTDESK = "FRONTDESK"
BANK = "BANK"
DRIVER = "DRIVER"
ONLINE = "ONLINE"
MARKETING = "MARKETING"
HEAD_OF_OPERATIONS = "HEAD OF OPERATIONS"

ACTIVE = "ACTIVE"
RELEASED = "RELEASED"
SUSPENDED = "SUSPENDED"
LEAVE = "LEAVE"

DOLLAR = "DOLLAR"
NAIRA = "NAIRA"
POUND = "POUND"
EURO = "EURO"

CASH = "CASH"
TRANSFER = "TRANSFER"
DEPOSIT = "DEPOSIT"
CASH_AND_TRANSFER = "CASH AND TRANSFER"


SENT = "SENT"
INITIATED = "INITIATED"
APPROVED = "APPROVED"
FAILED = "FAILED"

RECEIVING = 'RECEIVING'
GIVING = 'GIVING'

SALES = "SALES"
PURCHASE = "PURCHASE"
CROSS_CURRENCY = "CROSS CURRENCY"

SINGLE_PAYMENT = 'SINGLE PAYMENT'
DOUBLE_PAYMENT = 'DOUBLE PAYMENT'

RECIEVABLE = "RECIEVABLE"
PAYABLE = "PAYABLE"

ZENITH_BANK = "ZENITH BANK"
PROVIDUS_BANK = "PROVIDUS BANK"

REQUEST = "REQUEST"
SEND = "SEND"

EMPLOYEE_STATIONS = (
    (INTERN, "INTERN"),
    (FRONTDESK, "FRONT DESK"),
    (BANK, "BANK"),
    (DRIVER, "DRIVER"),
    (ONLINE, "ONLINE"),
    (MARKETING, "MARKETING"),
    (HEAD_OF_OPERATIONS, "HEAD OF OPERATIONS"),
)
EMPLOYEE_STATUS = (
    (ACTIVE, "ACTIVE"),
    (RELEASED, "RELEASED"),
    (SUSPENDED, "SUSPENSION"),
    (LEAVE, "LEAVE"),
)

CURRENCIES = (
    (NAIRA, "NAIRA"),
    (DOLLAR, "DOLLAR"),
    (POUND, "POUND"),
    (EURO, "EURO"),
)

MODE = (
    (CASH, "CASH"),
    (TRANSFER, "TRANSFER"),
    (DEPOSIT, "DEPOSIT"), 
    (CASH_AND_TRANSFER, "CASH AND TRANSFER")
)

TRANSACTION_STATUS = (
    (SENT, "SENT"),
    (INITIATED, "INITIATED"),
    (APPROVED, "APPROVED"),
    (FAILED, "FAILED"),
)

CATEGORIES = (
    (SALES, "SALES"),
    (PURCHASE, "PURCHASE"),
    (CROSS_CURRENCY, "CROSS CURRENCY"),
    
    
)

DEBTORS = (
    (RECIEVABLE, "RECIEVABLE"),
    (PAYABLE, "PAYABLE"),
)
BANKS = ((ZENITH_BANK, "ZENITH BANK"), (PROVIDUS_BANK, "PROVIDUS BANK"))

BENEFICIARIES = ((SINGLE_PAYMENT, 'SINGLE PAYMENT'), (DOUBLE_PAYMENT, 'DOUBLE PAYMENT'))

STATUS = ((RECEIVING, 'RECEIVING'), (GIVING, 'GIVING'))