from tkinter import SINGLE


FRONTDESK1 = "FRONTDESK1"
FRONTDESK2 = "FRONTDESK2"
FRONTDESK3 = "FRONTDESK3"
FRONTDESK4 = "FRONTDESK4"
BANK = "BANK"
DRIVER = "DRIVER"
ONLINE = "ONLINE"
MARKETING = "MARKETING"
HEAD_OF_OPERATIONS = "HEAD OF OPERATIONS"

ACTIVE = "ACTIVE"
RELEASED = "RELEASED"
SUSPENDED = "SUSPENDED"
LEAVE = "LEAVE"

USD = "USD"
NGN = "NGN"
GBP = "GBP"
EUR = "EUR"

CASH = "CASH"
TRANSFER = "TRANSFER"
DEPOSIT = "DEPOSIT"
CASH_AND_TRANSFER = "CASH AND TRANSFER"


SENT = "SENT"
INITIATED = "INITIATED"
APPROVED = "APPROVED"
FAILED = "FAILED"

RECEIVING = 'RECEIVING'
GIVING = 'GIVING'

SALES = "SALES"
PURCHASE = "PURCHASE"
CROSS_CURRENCY = "CROSS CURRENCY"

SINGLE_PAYMENT = 'SINGLE PAYMENT'
DOUBLE_PAYMENT = 'DOUBLE PAYMENT'

RECIEVABLE = "RECIEVABLE"
PAYABLE = "PAYABLE"

ZENITH_BANK = "ZENITH BANK"
PROVIDUS_BANK = "PROVIDUS BANK"

REQUEST = "REQUEST"
SEND = "SEND"

EMPLOYEE_STATIONS = (
    (FRONTDESK1,"FRONTDESK1"),
(FRONTDESK2 , "FRONTDESK2"),
(FRONTDESK3 , "FRONTDESK3"),
(FRONTDESK4 , "FRONTDESK4"),
    (BANK, "BANK"),
    (DRIVER, "DRIVER"),
    (ONLINE, "ONLINE"),
    (MARKETING, "MARKETING"),
    (HEAD_OF_OPERATIONS, "HEAD OF OPERATIONS"),
)
EMPLOYEE_STATUS = (
    (ACTIVE, "ACTIVE"),
    (RELEASED, "RELEASED"),
    (SUSPENDED, "SUSPENSION"),
    (LEAVE, "LEAVE"),
)

CURRENCIES = (
    (NGN, "NGN"),
    (USD, "USD"),
    (GBP, "GBP"),
    (EUR, "EUR"),
)

MODE = (
    (CASH, "CASH"),
    (TRANSFER, "TRANSFER"),
    (DEPOSIT, "DEPOSIT"), 
    (CASH_AND_TRANSFER, "CASH AND TRANSFER")
)

TRANSACTION_STATUS = (
    (SENT, "SENT"),
    (INITIATED, "INITIATED"),
    (APPROVED, "APPROVED"),
    (FAILED, "FAILED"),
)

CATEGORIES = (
    (SALES, "SALES"),
    (PURCHASE, "PURCHASE"),
    (CROSS_CURRENCY, "CROSS CURRENCY"),
    
    
)

DEBTORS = (
    (RECIEVABLE, "RECIEVABLE"),
    (PAYABLE, "PAYABLE"),
)
BANKS = ((ZENITH_BANK, "ZENITH BANK"), (PROVIDUS_BANK, "PROVIDUS BANK"))

BENEFICIARIES = ((SINGLE_PAYMENT, 'SINGLE PAYMENT'), (DOUBLE_PAYMENT, 'DOUBLE PAYMENT'))

STATUS = ((RECEIVING, 'RECEIVING'), (GIVING, 'GIVING'))