# Generated by Django 4.0.1 on 2022-02-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=10, verbose_name='Account Number')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full Nmae')),
                ('address', models.TextField(max_length=1024, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
                ('status', models.CharField(choices=[('ATV', 'ACTIVE'), ('RLSD', 'RELEASED'), ('SUS', 'SUSPENSION'), ('LVE', 'LEAVE')], default='ATV', max_length=50, verbose_name='Status')),
                ('station', models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOP', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('station', models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOP', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaries', models.CharField(choices=[('SP', 'SINGLE PAYMENT'), ('DP', 'DOUBLE PAYMENT')], default='SP', max_length=30, verbose_name='beneficiaries')),
                ('customer_name1', models.CharField(max_length=1024, verbose_name='Customer Name 1')),
                ('account_number1', models.CharField(max_length=10, verbose_name='Account Number 1')),
                ('bank_name1', models.CharField(max_length=100, verbose_name='Bank Name 1')),
                ('customer_name2', models.CharField(blank=True, max_length=1024, verbose_name='Customer Name 2')),
                ('account_number2', models.CharField(blank=True, max_length=10, verbose_name='Account Number 2')),
                ('bank_name2', models.CharField(blank=True, max_length=100, verbose_name='Bank Name 2')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(max_length=1024, verbose_name='Address')),
                ('recieved', models.CharField(choices=[('USD', 'DOLLAR'), ('NGN', 'NAIRA'), ('GBP', 'POUND'), ('EUR', 'EURO')], default='USD', max_length=1024, verbose_name='Currency Recieved')),
                ('amount_recieved', models.FloatField(default=0.0, verbose_name='Amount Recieved')),
                ('mode', models.CharField(choices=[('CSH', 'CASH'), ('TRF', 'TRANSFER'), ('DEP', 'DEPOSIT')], default='CSH', max_length=1024, verbose_name='Cash or Transfer')),
                ('rate', models.FloatField(default=0.0, verbose_name='Rate of Exchange')),
                ('amount_given', models.FloatField(default=0.0, verbose_name='Amount given')),
                ('amount_transfered', models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('initiator', models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOP', 'HEAD OF OPERATIONS')], default='FD', max_length=30, verbose_name='Station')),
                ('status', models.CharField(choices=[('SNT', 'SENT'), ('INI', 'INITIATED'), ('APRVD', 'APPROVED')], default='SNT', max_length=1024, verbose_name='Tansaction Status')),
                ('transaction_type', models.CharField(choices=[('SLS', 'SALES'), ('PUR', 'PURCHASE')], default='PUR', max_length=1024, verbose_name='Type of Transaction')),
                ('profit', models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
        ),
    ]
