# Generated by Django 4.0.1 on 2023-05-24 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full Nmae')),
                ('address', models.TextField(max_length=1024, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RELEASED', 'RELEASED'), ('SUSPENDED', 'SUSPENSION'), ('LEAVE', 'LEAVE')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('station', models.CharField(choices=[('FRONTDESK1', 'FRONTDESK1'), ('FRONTDESK2', 'FRONTDESK2'), ('FRONTDESK3', 'FRONTDESK3'), ('FRONTDESK4', 'FRONTDESK4'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], max_length=30, verbose_name='Station')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=30, verbose_name='Station')),
                ('buying', models.FloatField(default=0.0, verbose_name='Buying Rate')),
                ('selling', models.FloatField(default=0.0, verbose_name='Selling Rate')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=1024, verbose_name='Customer Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('receipt', models.FileField(upload_to='receipts/', verbose_name='Receipt')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('SINGLE PAYMENT', 'SINGLE PAYMENT'), ('DOUBLE PAYMENT', 'DOUBLE PAYMENT')], default='SINGLE PAYMENT', max_length=1024, verbose_name='Beneficiaries')),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Phone Number')),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('initiator', models.CharField(choices=[('FRONTDESK1', 'FRONTDESK1'), ('FRONTDESK2', 'FRONTDESK2'), ('FRONTDESK3', 'FRONTDESK3'), ('FRONTDESK4', 'FRONTDESK4'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK1', max_length=30, verbose_name='Station')),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED')], default='SENT', max_length=1024, verbose_name='Tansaction Status')),
                ('category', models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE'), ('CROSS CURRENCY', 'CROSS CURRENCY')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction')),
                ('profit', models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit')),
                ('receipt_number', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', length=5, max_length=5, prefix='', unique=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('station', models.CharField(choices=[('FRONTDESK1', 'FRONTDESK1'), ('FRONTDESK2', 'FRONTDESK2'), ('FRONTDESK3', 'FRONTDESK3'), ('FRONTDESK4', 'FRONTDESK4'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK1', max_length=30, verbose_name='Station')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('profit', models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReceiveGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVING', 'RECEIVING'), ('GIVING', 'GIVING')], default='RECEIVING', max_length=1024, verbose_name='Receiving or Giving')),
                ('bank_name', models.CharField(blank=True, max_length=2048, verbose_name='Bank Name')),
                ('account_name', models.CharField(blank=True, max_length=2048, verbose_name='Account Name')),
                ('currency', models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved')),
                ('cash', models.FloatField(default=0.0, verbose_name='Cash Recieved')),
                ('mode', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT'), ('CASH AND TRANSFER', 'CASH AND TRANSFER')], default='CASH', max_length=1024, verbose_name='Receive Mode')),
                ('transfer', models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered')),
                ('cash_rate', models.FloatField(default=0.0, verbose_name='Cash Rate')),
                ('transfer_rate', models.FloatField(blank=True, default=0.0, verbose_name='Transfer Rate')),
                ('selling_rate', models.FloatField(blank=True, default=0.0, verbose_name='Selling Rate')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_give', to='jamiyafx.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MoneyIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_total', models.FloatField(blank=True, default=0.0, verbose_name='Currency Total')),
                ('grand_total', models.FloatField(blank=True, default=0.0, verbose_name='Grand Total')),
                ('previous_total', models.FloatField(blank=True, default=0.0, verbose_name='Previous Total')),
                ('difference', models.FloatField(blank=True, default=0.0, verbose_name='Difference Of Balance')),
                ('expense', models.FloatField(blank=True, default=0.0, verbose_name='Expenses')),
                ('book_profit', models.FloatField(blank=True, default=0.0, verbose_name='Book Profit')),
                ('calculated_profit', models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit')),
                ('variance', models.FloatField(blank=True, default=0.0, verbose_name='Ledger Variance')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=1024, verbose_name='Customer Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('RECIEVABLE', 'RECIEVABLE'), ('PAYABLE', 'PAYABLE')], default='RECIEVABLE', max_length=1024, null=True, verbose_name='Status of Payment')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.report')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Customer Account Name ')),
                ('customer_account_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Customer Account Number ')),
                ('customer_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Bank Name')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount Transfered')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='jamiyafx.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=1024, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=1024, verbose_name='Account Name')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currencies', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
