# Generated by Django 4.0.1 on 2022-02-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
