# Generated by Django 4.0.1 on 2022-02-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='closingbalance',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['date_joined']},
        ),
        migrations.AlterModelOptions(
            name='moneyin',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='moneyout',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='closingbalance',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='moneyin',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='moneyout',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='openingbalance',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
