# Generated by Django 4.0.1 on 2022-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0003_alter_account_options_alter_closingbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date Added'),
        ),
    ]
