# Generated by Django 4.0.1 on 2023-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0005_alter_transaction_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='receivegive',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=1024, verbose_name='Currency Recieved'),
        ),
    ]
