# Generated by Django 4.0.1 on 2023-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0006_alter_rate_currency_alter_receivegive_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='euro',
            new_name='eur',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='pound',
            new_name='gbp',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='naira',
            new_name='ngn',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='dollar',
            new_name='usd',
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=30, verbose_name='Currency'),
        ),
    ]
