# Generated by Django 4.0.1 on 2022-02-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0007_alter_account_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.AlterModelOptions(
            name='closingbalance',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='moneyin',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='moneyout',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created']},
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying', models.FloatField(default=0.0, verbose_name='Buying Rate')),
                ('selling', models.FloatField(default=0.0, verbose_name='Selling Rate')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=1024, verbose_name='Customer Name')),
                ('status', models.CharField(choices=[('RCV', 'RECIEVABLE'), ('PYBL', 'PAYABLE')], default='RCV', max_length=1024, verbose_name='Status of Payment')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency')),
            ],
        ),
    ]
