# Generated by Django 4.0.1 on 2023-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0007_rename_euro_currency_eur_rename_pound_currency_gbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='ngn',
            field=models.FloatField(default=0.0, verbose_name='ngn Balance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
