# Generated by Django 4.0.1 on 2022-02-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0008_currency_alter_closingbalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='currency',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency'),
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='status',
            field=models.CharField(choices=[('RCV', 'RECIEVABLE'), ('PYBL', 'PAYABLE')], default='RCV', max_length=1024, null=True, verbose_name='Status of Payment'),
        ),
    ]
