# Generated by Django 4.0.1 on 2022-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0009_alter_customerledger_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='currency',
        ),
        migrations.AddField(
            model_name='customerledger',
            name='dollar',
            field=models.FloatField(default=0.0, verbose_name='Dollar Balance'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='euro',
            field=models.FloatField(default=0.0, verbose_name='Euro Balance'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='naira',
            field=models.FloatField(default=0.0, verbose_name='Naira Balance'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='pound',
            field=models.FloatField(default=0.0, verbose_name='Pound Balance'),
        ),
    ]
