# Generated by Django 4.0.1 on 2022-02-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0010_remove_customerledger_currency_customerledger_dollar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='buying',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='selling',
        ),
        migrations.AddField(
            model_name='rate',
            name='dollar_buying',
            field=models.FloatField(default=0.0, verbose_name='Dollar Buying Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='dollar_selling',
            field=models.FloatField(default=0.0, verbose_name='Dollar Selling Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='euro_buying',
            field=models.FloatField(default=0.0, verbose_name='Euro Buying Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='euro_selling',
            field=models.FloatField(default=0.0, verbose_name='Euro Selling Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='pound_buying',
            field=models.FloatField(default=0.0, verbose_name='Pound Buying Rate'),
        ),
        migrations.AddField(
            model_name='rate',
            name='pound_selling',
            field=models.FloatField(default=0.0, verbose_name='Pound Selling Rate'),
        ),
    ]
