# Generated by Django 4.0.1 on 2022-02-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0011_remove_rate_buying_remove_rate_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='customerledger',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='dollar_buying',
            new_name='buying',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='dollar_selling',
            new_name='selling',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='euro_buying',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='euro_selling',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='pound_buying',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='pound_selling',
        ),
        migrations.AddField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLAR'), ('NGN', 'NAIRA'), ('GBP', 'POUND'), ('EUR', 'EURO')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOO', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOO', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.CharField(choices=[('INT', 'INTERN'), ('FD', 'FRONT DESK'), ('BNK', 'BANK'), ('DRV', 'DRIVER'), ('ONL', 'ONLINE'), ('HOM', 'HEAD OF MARKETING'), ('HOO', 'HEAD OF OPERATIONS')], default='FD', max_length=30, verbose_name='Station'),
        ),
    ]
