# Generated by Django 4.0.1 on 2022-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0012_alter_currency_options_alter_customerledger_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='status',
            field=models.CharField(choices=[('RECIEVABLE', 'RECIEVABLE'), ('PAYABLE', 'PAYABLE')], default='RCV', max_length=1024, null=True, verbose_name='Status of Payment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RELEASED', 'RELEASED'), ('SUSPENDED', 'SUSPENSION'), ('LEAVE', 'LEAVE')], default='ATV', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='buying',
            field=models.FloatField(default=0.0, verbose_name='Buying Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('DOLLAR', 'DOLLAR'), ('NAIRA', 'NAIRA'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='selling',
            field=models.FloatField(default=0.0, verbose_name='Selling Rate'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiaries',
            field=models.CharField(choices=[('SINGLEPAYMENT', 'SINGLE PAYMENT'), ('DOUBLEPAYMENT', 'DOUBLE PAYMENT')], default='SP', max_length=30, verbose_name='beneficiaries'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='FD', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT')], default='CSH', max_length=1024, verbose_name='Cash or Transfer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recieved',
            field=models.CharField(choices=[('DOLLAR', 'DOLLAR'), ('NAIRA', 'NAIRA'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='USD', max_length=1024, verbose_name='Currency Recieved'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('APPROVED', 'APPROVED')], default='SNT', max_length=1024, verbose_name='Tansaction Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE')], default='PUR', max_length=1024, verbose_name='Type of Transaction'),
        ),
    ]
