# Generated by Django 4.0.1 on 2022-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0013_alter_customerledger_status_alter_employee_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='INT', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recieved',
            field=models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='USD', max_length=1024, verbose_name='Currency Recieved'),
        ),
    ]
