# Generated by Django 4.0.1 on 2022-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0015_alter_rate_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='account name', max_length=1024, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(max_length=1024, verbose_name='Bank Name'),
        ),
    ]
