# Generated by Django 4.0.1 on 2022-02-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0016_remove_account_account_number_account_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('recieveble', models.FloatField(default=0.0, verbose_name='Recievable Balance')),
                ('currency_total', models.FloatField(default=0.0, verbose_name='Currency Total')),
                ('grand_total', models.FloatField(default=0.0, verbose_name='Grand Total')),
                ('previous_total', models.FloatField(default=0.0, verbose_name='Previous Total')),
                ('difference', models.FloatField(default=0.0, verbose_name='Difference Of Balance')),
                ('expenses', models.FloatField(default=0.0, verbose_name='Expenses')),
                ('book_profit', models.FloatField(default=0.0, verbose_name='Book Profit')),
                ('calculated_profit', models.FloatField(default=0.0, verbose_name='Calculated Profit')),
                ('variance', models.FloatField(default=0.0, verbose_name='Ledger Variance')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
