# Generated by Django 4.0.1 on 2022-02-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0017_generalledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='recieveble',
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='book_profit',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Book Profit'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='calculated_profit',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='currency_total',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Currency Total'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='difference',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Difference Of Balance'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='dollar',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Dollar Balance'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='euro',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Euro Balance'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='expenses',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='grand_total',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='naira',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Naira Balance'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='pound',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Pound Balance'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='previous_total',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Previous Total'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='variance',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Ledger Variance'),
        ),
    ]
