# Generated by Django 4.0.1 on 2022-02-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0018_remove_generalledger_recieveble_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='previous_total',
        ),
    ]
