# Generated by Django 4.0.1 on 2022-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0020_alter_rate_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='generalledger',
            old_name='expenses',
            new_name='expense',
        ),
    ]
