# Generated by Django 4.0.1 on 2022-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0021_alter_currency_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
