# Generated by Django 4.0.1 on 2022-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0022_customerledger_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='customer',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED')], default='SNT', max_length=1024, verbose_name='Tansaction Status'),
        ),
    ]
