# Generated by Django 4.0.1 on 2022-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0023_alter_customerledger_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('CROSS', 'CROSS')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='INTERN', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RELEASED', 'RELEASED'), ('SUSPENDED', 'SUSPENSION'), ('LEAVE', 'LEAVE')], default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiaries',
            field=models.CharField(choices=[('SINGLEPAYMENT', 'SINGLE PAYMENT'), ('DOUBLEPAYMENT', 'DOUBLE PAYMENT')], default='SINGLEPAYMENT', max_length=30, verbose_name='beneficiaries'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recieved',
            field=models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved'),
        ),
    ]
