# Generated by Django 4.0.1 on 2022-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0024_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerledger',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_of_transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiaries',
            field=models.CharField(choices=[('SINGLE_PAYMENT', 'SINGLE PAYMENT'), ('DOUBLE_PAYMENT', 'DOUBLE PAYMENT')], default='SINGLE_PAYMENT', max_length=30, verbose_name='beneficiaries'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE'), ('CROSS', 'CROSS')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT')], default='CASH', max_length=1024, verbose_name='Cash or Transfer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED')], default='SENT', max_length=1024, verbose_name='Tansaction Status'),
        ),
    ]
