# Generated by Django 4.0.1 on 2022-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0025_alter_customerledger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='given',
            field=models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction'),
        ),
    ]
