# Generated by Django 4.0.1 on 2022-02-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0026_transaction_given_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='profit',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Calculated Profit'),
        ),
    ]
