# Generated by Django 4.0.1 on 2022-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0027_report_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='given',
            new_name='currency_given',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='recieved',
            new_name='currency_recieved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mode',
        ),
        migrations.AddField(
            model_name='transaction',
            name='given_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT')], default='CASH', max_length=1024, verbose_name='How Money was given'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recieve_mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT')], default='CASH', max_length=1024, verbose_name='How Money was Recieved'),
        ),
    ]
