# Generated by Django 4.0.1 on 2022-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0028_rename_given_transaction_currency_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_from',
            field=models.CharField(choices=[('ZENITHBANK', 'ZENITH BANK'), ('PROVIDUSBANK', 'PROVIDUS BANK')], default='ZENITHBANK', max_length=50, verbose_name='Payment From'),
        ),
        migrations.AlterField(
            model_name='customerledger',
            name='status',
            field=models.CharField(choices=[('RECIEVABLE', 'RECIEVABLE'), ('PAYABLE', 'PAYABLE')], default='RECIEVABLE', max_length=1024, null=True, verbose_name='Status of Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('HEADOFMARKETING', 'HEAD OF MARKETING'), ('HEADOFOPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK', max_length=30, verbose_name='Station'),
        ),
    ]
