# Generated by Django 4.0.1 on 2022-02-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0029_transaction_paid_from_alter_customerledger_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_from',
            field=models.CharField(choices=[('ZENITH BANK', 'ZENITH BANK'), ('PROVIDUS BANK', 'PROVIDUS BANK')], default='ZENITH BANK', max_length=50, verbose_name='Payment From'),
        ),
    ]
