# Generated by Django 4.0.1 on 2022-02-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0030_alter_transaction_paid_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='given_mode',
            new_name='give_mode',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('DONE', 'APPROVED'), ('FAILED', 'FAILED')], default='SENT', max_length=1024, verbose_name='Tansaction Status'),
        ),
    ]
