# Generated by Django 4.0.1 on 2022-02-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0032_transaction_transfered_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_given',
            new_name='cash_given',
        ),
    ]
