# Generated by Django 4.0.1 on 2022-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0033_rename_amount_given_transaction_cash_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_from',
            field=models.CharField(choices=[('ZENITH BANK', 'ZENITH BANK'), ('PROVIDUS BANK', 'PROVIDUS BANK')], default='ZENITH BANK', max_length=50, null=True, verbose_name='Payment From'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfered_to',
            field=models.CharField(choices=[('ZENITH BANK', 'ZENITH BANK'), ('PROVIDUS BANK', 'PROVIDUS BANK')], default='PROVIDUS BANK', max_length=50, null=True, verbose_name='Transfered To'),
        ),
    ]
