# Generated by Django 4.0.1 on 2022-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0034_alter_transaction_paid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='previous_total',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Previous Total'),
        ),
    ]
