# Generated by Django 4.0.1 on 2022-02-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0036_alter_account_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
