# Generated by Django 4.0.1 on 2022-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0037_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReeipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=1024, verbose_name='Bank Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('receipt', models.FileField(upload_to='receipts/% Y/% m/% d/')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
    ]
