# Generated by Django 4.0.1 on 2022-02-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0038_customerreeipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerReeipt',
            new_name='Reeipt',
        ),
    ]
