# Generated by Django 4.0.1 on 2022-02-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0039_rename_customerreeipt_reeipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reeipt',
            new_name='Receipt',
        ),
    ]
