# Generated by Django 4.0.1 on 2022-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0040_rename_reeipt_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(max_length=1024, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=models.FileField(upload_to='receipts/', verbose_name='Receipt'),
        ),
    ]
