# Generated by Django 4.0.1 on 2023-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0041_alter_receipt_customer_name_alter_receipt_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='Date Last Updated'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], default='INTERN', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK', max_length=30, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('FRONTDESK', 'FRONT DESK'), ('BANK', 'BANK'), ('DRIVER', 'DRIVER'), ('ONLINE', 'ONLINE'), ('MARKETING', 'MARKETING'), ('HEAD OF OPERATIONS', 'HEAD OF OPERATIONS')], default='FRONTDESK', max_length=30, verbose_name='Station'),
        ),
    ]
