# Generated by Django 4.0.1 on 2023-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0042_alter_customerledger_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Last Updated'),
        ),
    ]
