# Generated by Django 4.0.1 on 2023-04-16 18:53

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0044_alter_customerledger_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', blank=True, length=5, max_length=5, null=True, prefix='', unique=True),
        ),
    ]
