# Generated by Django 4.0.1 on 2023-04-16 19:30

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0045_transaction_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', blank=True, length=5, max_length=5, null=True, prefix='', unique=True),
        ),
    ]
