# Generated by Django 4.0.1 on 2023-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0047_alter_transaction_receipt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_recieved',
            new_name='cash_received',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency_recieved',
            new_name='currency_received',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_transfered',
            new_name='give_amount_transfered',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='recieve_mode',
            new_name='receive_mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfered_to',
        ),
        migrations.AddField(
            model_name='transaction',
            name='give_account_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='give_bank_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_account_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_amount_transfered',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_bank_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_number1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Account Number 1'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_name1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Name 1'),
        ),
    ]
