# Generated by Django 4.0.1 on 2023-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0048_rename_amount_recieved_transaction_cash_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naira', models.FloatField(default=0.0, verbose_name='Naira Balance')),
                ('dollar', models.FloatField(default=0.0, verbose_name='Dollar Balance')),
                ('pound', models.FloatField(default=0.0, verbose_name='Pound Balance')),
                ('euro', models.FloatField(default=0.0, verbose_name='Euro Balance')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='dollar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='euro',
        ),
        migrations.RemoveField(
            model_name='account',
            name='naira',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pound',
        ),
    ]
