# Generated by Django 4.0.1 on 2023-04-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0050_remove_closingbalance_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='closing_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_balance', to='jamiyafx.currency'),
        ),
        migrations.AddField(
            model_name='report',
            name='money_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_in', to='jamiyafx.currency'),
        ),
        migrations.AddField(
            model_name='report',
            name='money_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_out', to='jamiyafx.currency'),
        ),
        migrations.AddField(
            model_name='report',
            name='opening_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to='jamiyafx.currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=1024, verbose_name='Account Name'),
        ),
    ]
