# Generated by Django 4.0.1 on 2023-04-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0051_report_closing_balance_report_money_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='money_in',
        ),
        migrations.RemoveField(
            model_name='report',
            name='money_out',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_balance',
        ),
    ]
