# Generated by Django 4.0.1 on 2023-04-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0052_remove_report_closing_balance_remove_report_money_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currencies',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamiyafx.currency'),
        ),
    ]
