# Generated by Django 4.0.1 on 2023-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0053_alter_account_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_rate',
            field=models.FloatField(default=0.0, verbose_name='Cash Rate'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_rate',
            field=models.FloatField(default=0.0, verbose_name='Transfer Rate'),
        ),
    ]
