# Generated by Django 4.0.1 on 2023-05-05 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0054_remove_transaction_rate_transaction_cash_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_given',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_received',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency_given',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency_received',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='give_account_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='give_amount_transfered',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='give_bank_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='give_mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receive_account_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receive_amount_transfered',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receive_bank_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receive_mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_rate',
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_bank_name', models.CharField(blank=True, max_length=2048, verbose_name='Bank Name')),
                ('receive_account_name', models.CharField(blank=True, max_length=2048, verbose_name='Account Name')),
                ('currency_received', models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved')),
                ('cash_received', models.FloatField(default=0.0, verbose_name='Amount Recieved')),
                ('receive_mode', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT'), ('DOUBLE TRANSFER', 'DOUBLE TRANSFER'), ('CASH AND TRANSFER', 'CASH AND TRANSFER'), ('CASH AND DOUBLE TRANSFER', 'CASH AND DOUBLE TRANSFER')], default='CASH', max_length=1024, verbose_name='Receive Mode')),
                ('receive_amount_transfered', models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered')),
                ('cash_rate', models.FloatField(default=0.0, verbose_name='Cash Rate')),
                ('transfer_rate', models.FloatField(blank=True, default=0.0, verbose_name='Transfer Rate')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='jamiyafx.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_bank_name', models.CharField(blank=True, max_length=1024, verbose_name='Bank Name')),
                ('give_account_name', models.CharField(blank=True, max_length=1024, verbose_name='Account Name')),
                ('give_mode', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT'), ('DOUBLE TRANSFER', 'DOUBLE TRANSFER'), ('CASH AND TRANSFER', 'CASH AND TRANSFER'), ('CASH AND DOUBLE TRANSFER', 'CASH AND DOUBLE TRANSFER')], default='CASH', max_length=1024, verbose_name='Give Mode')),
                ('currency_given', models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved')),
                ('cash_given', models.FloatField(default=0.0, verbose_name='Amount given')),
                ('give_amount_transfered', models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered')),
                ('selling_rate', models.FloatField(blank=True, default=0.0, verbose_name='Selling Rate')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving', to='jamiyafx.transaction')),
            ],
        ),
    ]
