# Generated by Django 4.0.1 on 2023-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0055_remove_transaction_beneficiaries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giving',
            old_name='transaction',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='receiving',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
