# Generated by Django 4.0.1 on 2023-05-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0056_rename_transaction_giving_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giving',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='receiving',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
