# Generated by Django 4.0.1 on 2023-05-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0057_rename_transaction_id_giving_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_name', models.CharField(max_length=1024, verbose_name='Customer Account Name ')),
                ('customer_account_number', models.CharField(blank=True, max_length=10, verbose_name='Customer Account Number ')),
                ('customer_bank_name', models.CharField(blank=True, max_length=100, verbose_name='Customer Bank Name')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiaries',
            field=models.CharField(choices=[('SINGLE PAYMENT', 'SINGLE PAYMENT'), ('DOUBLE PAYMENT', 'DOUBLE PAYMENT'), ('TRIPLE PAYMENT', 'TRIPLE_PAYMENT')], default='SINGLE PAYMENT', max_length=1024, verbose_name='Beneficiaries'),
        ),
        migrations.AlterField(
            model_name='giving',
            name='cash_given',
            field=models.FloatField(default=0.0, verbose_name='Cash given'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='cash_received',
            field=models.FloatField(default=0.0, verbose_name='Cash Recieved'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Description'),
        ),
    ]
