# Generated by Django 4.0.1 on 2023-05-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0058_beneficiary_transaction_beneficiaries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_number1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_number2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_name1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_name2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_name2',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to='jamiyafx.transaction'),
        ),
    ]
