# Generated by Django 4.0.1 on 2023-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0059_remove_transaction_account_number1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='amount_transfered',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiaries',
            field=models.CharField(choices=[('SINGLE PAYMENT', 'SINGLE PAYMENT'), ('DOUBLE PAYMENT', 'DOUBLE PAYMENT')], default='SINGLE PAYMENT', max_length=1024, verbose_name='Beneficiaries'),
        ),
    ]
