# Generated by Django 4.0.1 on 2023-05-08 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0060_beneficiary_amount_transfered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVING', 'RECEIVING'), ('GIVING', 'GIVING')], default='RECEIVING', max_length=1024, verbose_name='Receiving or Giving')),
                ('bank_name', models.CharField(blank=True, max_length=2048, verbose_name='Bank Name')),
                ('account_name', models.CharField(blank=True, max_length=2048, verbose_name='Account Name')),
                ('currency', models.CharField(choices=[('NAIRA', 'NAIRA'), ('DOLLAR', 'DOLLAR'), ('POUND', 'POUND'), ('EURO', 'EURO')], default='DOLLAR', max_length=1024, verbose_name='Currency Recieved')),
                ('cash', models.FloatField(default=0.0, verbose_name='Cash Recieved')),
                ('mode', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT')], default='CASH', max_length=1024, verbose_name='Receive Mode')),
                ('amount_transfered', models.FloatField(blank=True, default=0.0, verbose_name='Amount Transfered')),
                ('cash_rate', models.FloatField(default=0.0, verbose_name='Cash Rate')),
                ('transfer_rate', models.FloatField(blank=True, default=0.0, verbose_name='Transfer Rate')),
                ('selling_rate', models.FloatField(blank=True, default=0.0, verbose_name='Selling Rate')),
                ('date_created', models.DateField(default=datetime.datetime.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Updated')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='jamiyafx.transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Giving',
        ),
        migrations.DeleteModel(
            name='Receiving',
        ),
    ]
