# Generated by Django 4.0.1 on 2023-05-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0061_receivegive_remove_receiving_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivegive',
            old_name='amount_transfered',
            new_name='transfer',
        ),
        migrations.AlterField(
            model_name='receivegive',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_give', to='jamiyafx.transaction'),
        ),
    ]
