# Generated by Django 4.0.1 on 2023-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0062_rename_amount_transfered_receivegive_transfer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='amount_transfered',
            new_name='transfer',
        ),
    ]
