# Generated by Django 4.0.1 on 2023-05-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0063_rename_amount_transfered_beneficiary_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_account_name',
            new_name='customer_account_name1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_account_number',
            new_name='customer_account_number1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_bank_name',
            new_name='customer_bank_name1',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='transfer',
            new_name='transfer_amount1',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='customer_account_name2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Customer Account Name '),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='customer_account_number2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Customer Account Number '),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='customer_bank_name2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Bank Name'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='transfer_amount2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount Transfered'),
        ),
    ]
