# Generated by Django 4.0.1 on 2023-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0064_rename_customer_account_name_beneficiary_customer_account_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='address',
            field=models.TextField(max_length=1024, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
