# Generated by Django 4.0.1 on 2023-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0065_remove_transaction_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='transfer_amount2',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_account_name2',
            new_name='customer_account_name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_account_number2',
            new_name='customer_account_number',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='customer_bank_name2',
            new_name='customer_bank_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='beneficiaries',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='customer_account_name1',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='customer_account_number1',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='customer_bank_name1',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='transfer_amount1',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.TextField(max_length=1024, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
