# Generated by Django 4.0.1 on 2023-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0066_rename_transfer_amount2_beneficiary_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
    ]
