# Generated by Django 4.0.1 on 2023-05-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamiyafx', '0067_remove_transaction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='jamiyafx.transaction'),
        ),
        migrations.AlterField(
            model_name='receivegive',
            name='mode',
            field=models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('DEPOSIT', 'DEPOSIT'), ('CASH AND TRANSFER', 'CASH AND TRANSFER')], default='CASH', max_length=1024, verbose_name='Receive Mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALES', 'SALES'), ('PURCHASE', 'PURCHASE'), ('CROSS CURRENCY', 'CROSS CURRENCY')], default='PURCHASE', max_length=1024, verbose_name='Category of Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('INITIATED', 'INITIATED'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED')], default='SENT', max_length=1024, verbose_name='Tansaction Status'),
        ),
    ]
